apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUyT0RZMk16YzJOVEFlRncweE9UQTVNVFl4T1RVMk1EVmFGdzB5T1RBNU1UTXhPVFUyTURWYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUyT0RZMk16YzJOVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQklEMEUwUUdNR0tCN0pWOU8zVGltRElRQVYwUkxGZkRXb25jUDlBbnRXWW4KQkF4SEY4V2hTQURoOWRySXhKMU1TSXQ2QVFXYUlWeGJaMmhZaDc3OWg2U2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDN2ludDU0REdKCnowUUh5eGE4NDJkTG12U1BLNytyY3MrSlNGVnlIVU90UGdJZ1BQVk83cFNIVjVyUThFbVZtMWV2YkllV3lpTmEKblhWbDZsR0VzSDhmSk1RPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: cattle-system
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: d8d904aabe276342e379ac93b5db974a
    username: admin
