version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.138
    container_name: jenkins
    volumes:
      - data:/var/jenkins_home/
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS=-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
volumes:
  data:
